Feature/marquee-section
its-rav/namvietstore-fe pull request #15
Opened 2023-07-15 07:37 UTC by phongduong-dp

# Description

Create marquee section for logos

# Checklist

- [x] This is a breaking changes?

2023-07-21 08:34 UTC, its-rav commented on packages/core-components/src/components/sections/MarqueeSection.tsx
> +  content?: MarqueeContentType[];
- sửa lại naming cho list
- sao cái này nullable ta

2023-07-21 08:36 UTC, its-rav requested changes
can I have a video showing how this component should've render?

2023-07-21 08:36 UTC, its-rav commented on packages/core-components/src/components/sections/MarqueeSection.tsx
> +      {children}
children có cần thiết k bạn

2023-07-24 14:28 UTC, phongduong-dp commented
> can I have a video showing how this component should've render?

Hi @its-rav  please see below videos.

**Default**

https://github.com/its-rav/namvietstore-fe/assets/92157056/f219d5f0-c1b4-4b98-9c31-3cb761153988

**No Logo**

https://github.com/its-rav/namvietstore-fe/assets/92157056/ce4c552c-e69e-41ee-b381-a97983a6a65e

**Small screen size**

https://github.com/its-rav/namvietstore-fe/assets/92157056/b36af666-1aa8-495c-8425-91020f5657bd

2023-08-06 07:43 UTC, its-rav requested changes

2023-08-06 07:43 UTC, its-rav commented on packages/core-components/src/components/sections/index.ts
> +  type MarqueeItemsType,
...Props fren

2023-08-06 07:43 UTC, its-rav commented on packages/core-components/src/components/sections/index.ts
>    type StatisticItemsType,
đây nữa nè, ủa bữa chưa fix hả, mà nó phải là StatisticItemType chứ ta

2023-08-19 13:51 UTC, its-rav approved these changes

2023-08-21 13:51 UTC, merged