feat: intro panel component and story
its-rav/namvietstore-fe pull request #18
Opened 2023-08-15 14:37 UTC by phongduong-dp

# Description

Create intro panel component

# Checklist

- [ ] This is a breaking changes?

2023-08-19 13:45 UTC, its-rav commented
u got screenshots or somethin? @phongduong-dp

2023-08-20 03:18 UTC, phongduong-dp commented
> u got screenshots or somethin? @phongduong-dp

@its-rav please see below images

***Normal***

![Normal](https://github.com/its-rav/namvietstore-fe/assets/92157056/57630692-da4e-4467-b2cb-f001a309518a)

***Small screen size***

![Small](https://github.com/its-rav/namvietstore-fe/assets/92157056/6cbfbb3f-7650-40df-8ca9-c4d8457488c7)

2023-08-20 04:28 UTC, its-rav requested changes

2023-08-20 04:28 UTC, its-rav commented on packages/core-components/src/components/sections/IntroPanel.tsx
> +export type introPanelItemType = {
this one should be **I**ntroPanelItemType

2023-08-20 04:28 UTC, its-rav commented on packages/core-components/src/components/sections/IntroPanel.tsx
> +        children='Đọc thêm'
pls also add this in the prop, so that we can do language switch. Ex moreButtonText

2023-09-01 07:10 UTC, its-rav approved these changes

2023-09-06 13:55 UTC, merged