Feature/next-app-router
its-rav/namvietstore-fe pull request #23
Opened 2023-09-26 15:51 UTC by phongduong-dp

# Description

Setup nextJS app router contains home page and product page.

Setup Eslint and Prettier (same as in package/core-ui)

All "use-client" decorative is only used for an easy setup.

# Checklist

- [ ] This is a breaking changes?

2023-10-06 15:26 UTC, its-rav requested changes
🤙

2023-10-07 03:32 UTC, phongduong-dp commented on apps/next-app/package.json
> +    "eslint-config-prettier": "^8.8.0",
@its-rav  to be honest, I have no idea, I just find eslint set up and it show me I need to install this packages. The rest is copied from our core-ui library

2023-10-07 04:55 UTC, its-rav approved these changes

2023-10-07 04:55 UTC, its-rav commented on apps/next-app/package.json
> +    "eslint-config-prettier": "^8.8.0",
👍 nvm, I'll fix it in another PR

2023-10-07 12:09 UTC, merged