Feature/category button
its-rav/namvietstore-fe pull request #25
Opened 2023-10-03 08:44 UTC by Neeze

# Description & Technical Solution

I Re-design the category menu button and split it into discrete reusable components.
Main button
Item button (Item button has default size and small Item button is used in sub menu)
Category Board is where submenus are rendered.
Demo in playground below!

All components work well on medium and large screen sizes. In small screen size, it is said that we must create new components for mobile.

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] Already rebased against main branch.

# Screenshots
demo behaviour
https://github.com/its-rav/namvietstore-fe/assets/60569049/e8a7fccc-0d20-4a1e-aa6e-546436e9b420

![Screenshot 2023-10-03 154231](https://github.com/its-rav/namvietstore-fe/assets/60569049/de2a63ee-5614-4217-9ca2-9a679bad2086)
![Screenshot 2023-10-03 154243](https://github.com/its-rav/namvietstore-fe/assets/60569049/5546bb1a-433e-4e74-8bae-e52b65a9c142)
![Screenshot 2023-10-03 154314](https://github.com/its-rav/namvietstore-fe/assets/60569049/4d72fc56-3ce5-4093-8f4c-616484ba7b38)
![Screenshot 2023-10-03 154218](https://github.com/its-rav/namvietstore-fe/assets/60569049/8dc39b9c-d1a6-49e4-b843-ba11fdfc6eec)

Provide screenshots or videos of the changes made if any.

2023-10-03 15:03 UTC, phongduong-dp commented on playground/src/CategoryMenuButton.stories.tsx
> +import {type ItemProps, CategoryItem} from "@namviet-fe/core-ui"
@Neeze delete unused import

2023-10-04 00:59 UTC, Neeze commented on playground/src/CategoryMenuButton.stories.tsx
> +import {type ItemProps, CategoryItem} from "@namviet-fe/core-ui"
I solved it

2023-10-04 12:25 UTC, its-rav commented
title size seems off to me. Too big

2023-10-04 12:26 UTC, its-rav commented
button missing border-radius !? This is why I want to reuse the Button component

2023-10-04 12:43 UTC, its-rav reviewed
How can we navigate on clicking to any of the items!?

2023-10-04 12:43 UTC, its-rav commented on packages/core-components/src/components/FeaturesCard.tsx
Why do we have changes related to Feature/Service Card

2023-10-04 12:43 UTC, its-rav commented on packages/core-components/src/components/category/CategoryProps.tsx
we don't have any jsx here so I guess .ts would be a better extension for this?

2023-10-04 12:43 UTC, its-rav commented on packages/core-components/src/components/category/CategoryUsage.tsx
> +const CategoryUsage: React.FC<CategoryMenu> = ({
lol, CategoryMenu/CategoryMenuComponent should be fine

2023-10-04 12:43 UTC, its-rav commented on packages/core-components/src/components/category/CategoryItem.tsx
> +  small,
what is this `small` prop. Not sure how can I understand this

2023-10-04 12:46 UTC, its-rav requested changes
Please double check your components, make sure others can understand and use it ?

2023-10-15 05:38 UTC, its-rav requested changes

2023-10-15 05:38 UTC, its-rav commented on packages/core-components/src/components/FeaturesCard.tsx
Why do you resolve this !? the change is still here !?

2023-10-15 05:38 UTC, its-rav commented on packages/core-components/src/components/category/CategoryItem.tsx
> +  small,
same question. Have you fixed this!? why do you mark this as resolved?!

2023-10-15 05:38 UTC, its-rav commented on packages/core-components/src/components/category/CategoryItem.tsx
> +            className={`text-black md:text-sm ${boldTitle ? 'font-bold' : ''}`}
I recall mentioning this earlier. Isn't isTitleBold better!?

2023-10-15 05:38 UTC, its-rav commented on playground/src/ServiceCard.stories.tsx
>  import "@namviet-fe/core-ui/dist/style.css";
same here. Unrelated changes

2023-10-15 05:38 UTC, its-rav commented on playground/.ladle/config.mjs
> +        xsmall: 320,
why do we have this change!? do we have any discussion on why should we have xsmall 320!?

2023-10-15 05:39 UTC, its-rav commented on packages/core-components/src/components/category/CategoryButton.tsx
> +import React from 'react';
this one good 🧠

2023-10-15 05:41 UTC, its-rav commented on packages/core-components/src/components/category/CategoryItem.tsx
> +  children: string;
children as string !? for `children` you can just do this
```
type ItemProps = {
    // ...props
} & PropsWithChildren;
```

2023-10-15 05:44 UTC, its-rav commented on packages/core-components/src/components/category/CategoryItem.tsx
> +  small,
I get what is `small` prop now. But still, why do we have to have this condition? Create another component and call it a day

2023-12-04 15:58 UTC, its-rav commented
close cause of inactivity

2024-01-06 07:27 UTC, closed without merging