Feature/search bar
its-rav/namvietstore-fe pull request #27
Opened 2023-10-10 16:06 UTC by phongduong-dp

# Description & Technical Solution

Create search bar component used for header on PC layout.
Component will work on Enter or by clicking search icon button.
Component is not responsive since another component for mobile will be created.
I tried to remove browser default behavior but it does not work.

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] Already rebased against main branch.

# Screenshots

***PC layout***

https://github.com/its-rav/namvietstore-fe/assets/92157056/aec9fb27-d030-4ff9-8205-ac7d185a61ed

2023-11-26 03:22 UTC, its-rav requested changes

2023-11-26 03:22 UTC, its-rav commented on packages/core-components/src/components/SearchBar.tsx
> +      onSubmit={handleSubmit}
How do we get the query text inside this handler

2023-11-26 03:22 UTC, its-rav commented on packages/core-components/src/components/SearchBar.tsx
> +  searchIcon: React.ReactNode;
do we really need this in the prop, as it is already a 'search icon'!?

2023-11-26 03:22 UTC, its-rav commented on playground/src/FeaturesCard.stories.tsx
> -    <FeaturesCard featuresCardItem={featuresCardItem} />{" "}
This change is not related to the feature, normally we should have this at another PR but we can let it slide this time

2023-11-26 03:22 UTC, its-rav commented on packages/core-components/src/components/SearchBar.tsx
> +  placeholders,
placeholder you mean?

2023-11-28 15:20 UTC, phongduong-dp commented on packages/core-components/src/components/SearchBar.tsx
> +  placeholders,
Placeholders is the string shows default inside the input box (the "Search all products" part).

I think we will have VN and EN version for this, so I put it as a prop.


![search](https://github.com/its-rav/namvietstore-fe/assets/92157056/b9a3ca20-e3d1-4056-bf85-93db890d3cb3)

2023-11-29 14:49 UTC, its-rav commented on packages/core-components/src/components/SearchBar.tsx
> +  placeholders,
the plural naming I mean

2023-11-29 14:50 UTC, its-rav commented on packages/core-components/src/components/SearchBar.tsx
> +  searchIcon: React.ReactNode;
pump this up

2023-11-29 14:50 UTC, its-rav commented on packages/core-components/src/components/SearchBar.tsx
> +  searchIcon: React.ReactNode;
nvm

2023-11-29 14:57 UTC, its-rav commented on packages/core-components/src/components/SearchBar.tsx
> +      onSubmit={handleSubmit}
normally we have name  attr in input tag, and when we submit the form, the field will automately submit with the corresponding field
In this case, I don't think we need form personally. We can expose out onSubmit with query text as the param and call it on button click, and even better, expose onQueryChange for whenever the input value change.

2023-11-29 15:01 UTC, its-rav commented on packages/core-components/src/components/SearchBar.tsx
> +      onSubmit={handleSubmit}
FYI, we can use `useRef`/`createRef` to get the value of the input at the time

2023-12-04 15:58 UTC, its-rav commented
conflict

2023-12-04 16:07 UTC, phongduong-dp commented
> conflict

solved

2023-12-21 09:30 UTC, its-rav approved these changes

2023-12-21 14:48 UTC, merged