Feature/statistic-section
its-rav/namvietstore-fe pull request #8
Opened 2023-06-18 07:05 UTC by phongduong-dp

# Description & Technical Solution

Create statistic section

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] Already rebased against main branch.

2023-06-18 08:19 UTC, its-rav requested changes

2023-06-18 08:19 UTC, its-rav commented on src/components/layout/StatisticSection.tsx
> +  content: ContentType[];
put this in plural for clearer variable context. e.g. contentItems, statisticItems

2023-06-18 08:19 UTC, its-rav commented on src/components/layout/Section.tsx
> +  [key: string]: string[];
use keyof VariantArr !? maybe

2023-06-18 08:19 UTC, its-rav commented on src/components/layout/Section.tsx
> +type SectionType = {
rename all of component props type to {componentName}Props => add a convention for all props type

2023-06-18 08:19 UTC, its-rav commented on src/components/layout/StatisticSection.tsx
> +  statistic: string;
should this be number!?

2023-07-21 08:19 UTC, phongduong-dp commented
@its-rav  Please review, Section.tsx has been delete because we have not used it yet. Only StatisticSection.tsx comments are picked up.

2023-07-21 08:42 UTC, its-rav approved these changes
lgtm

2023-07-21 11:40 UTC, merged